# Generated by Django 2.2.4 on 2022-07-12 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_auto_20220708_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_2',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem_3',
        ),
    ]
