# Generated by Django 2.2.4 on 2022-07-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_auto_20220711_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem_2',
            field=models.ImageField(blank=True, null=True, upload_to='produto_imagem/%Y/%m'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_3',
            field=models.ImageField(blank=True, null=True, upload_to='produto_imagem/%Y/%m'),
        ),
    ]
