# Generated by Django 2.2.4 on 2022-07-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='preco',
            field=models.FloatField(verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco_promocinal',
            field=models.FloatField(default=0, verbose_name='preço promocional'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variacao',
            field=models.CharField(max_length=100, verbose_name='Variação'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variacao_id',
            field=models.PositiveIntegerField(verbose_name='Variação id'),
        ),
    ]
